# Generated by Django 4.1.3 on 2022-11-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='numero',
        ),
    ]
