# Generated by Django 4.1.3 on 2022-11-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_produto_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
