# Generated by Django 4.1.3 on 2022-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_categoria_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='contador',
            field=models.IntegerField(default=0),
        ),
    ]
