# Generated by Django 4.1.3 on 2022-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categoria_contador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='contador',
        ),
        migrations.AddField(
            model_name='produto',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
