# Generated by Django 4.1.3 on 2022-12-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_categoria_contador_produto_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='numero',
        ),
    ]
