# Generated by Django 4.1.3 on 2022-12-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_produto_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
    ]
