# Generated by Django 4.1.3 on 2022-12-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_categoria_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='categoria',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
