# Generated by Django 4.1.3 on 2022-12-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_categoria_disponivel_categoria_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='disponivel',
            new_name='visible',
        ),
    ]
