# Generated by Django 4.1.3 on 2022-12-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_disponivel_produto_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='visible',
            new_name='disponivel',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='visible',
            new_name='disponivel',
        ),
    ]
